services:
  user_session_db:
    image: mysql:8.0
    container_name: user_session_db
    environment:
      MYSQL_DATABASE: user_session_db
      MYSQL_ROOT_PASSWORD: Front2Back!
      MYSQL_USER: finet_app
      MYSQL_PASSWORD: finet_password
    volumes:
      - ./user_session_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user_session_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

  stock_data_db:
    image: mysql:8.0
    container_name: stock_data_db
    environment:
      MYSQL_DATABASE: stock_data_db
      MYSQL_ROOT_PASSWORD: Front2Back!
      MYSQL_USER: finet_app
      MYSQL_PASSWORD: finet_password

    volumes:
      - ./stock_data_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - stock_data:/var/lib/mysql
    networks:
      - app_network
    restart: always

  finet:
    build:
      context: ..
      dockerfile: ./cmd/finet/dockerfile/finetDockerfile
    container_name: finet_app
    ports:
      - "8000:8000"
    environment:
      COOKIE_SECURE: "false"
      DB_USER_SESSION_HOST: user_session_db
      DB_USER_SESSION_PORT: 3306
      DB_USER_SESSION_NAME: user_session_db
      DB_USER_SESSION_USER: finet_app
      DB_USER_SESSION_PASSWORD: finet_password

      DB_STOCK_DATA_HOST: stock_data_db
      DB_STOCK_DATA_PORT: 3306
      DB_STOCK_DATA_NAME: stock_data_db
      DB_STOCK_DATA_USER: finet_app
      DB_STOCK_DATA_PASSWORD: finet_password
    networks:
      - app_network
    depends_on:
      user_session_db:
        condition: service_started
      stock_data_db:
        condition: service_started
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: ./dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - finet
    restart: always

volumes:
  user_session_data:
  stock_data:

networks:
  app_network:
    driver: bridge
